Gemspec/DuplicatedAssignment:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false
Layout/HashAlignment:
    Enabled: false
Layout/ParameterAlignment:
  Enabled: false
Layout/EndAlignment:
  EnforcedStyleAlignWith: "variable"
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/HeredocIndentation:
    Enabled: false
Layout/LineLength:
  Max: 100

Lint/NestedMethodDefinition:
  Enabled: false
Lint/RescueException:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Max: 6

Naming/MethodParameterName:
  Enabled: false

Style/AndOr:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/NonNilCheck:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: "double_quotes"
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
